let verbosB = [
    {
        verbo: 'ser', prs_1s: 'sou',
        prs_3s: 'é',
        prs_1p: 'somos',
        prs_3p: 'são',
        ptp_1s: 'fui',
        ptp_3s: 'foi',
        ptp_1p: 'fomos',
        ptp_3p: 'foram',
        pti_1s: 'era',
        pti_3s: 'era',
        pti_1p: 'éramos',
        pti_3p: 'eram',
        fps_1s: 'serei',
        fps_3s: 'será',
        fps_1p: 'seremos',
        fps_3p: 'serão',
        fpt_1s: 'seria',
        fpt_3s: 'seria',
        fpt_1p: 'seríamos',
        fpt_3p: 'seriam'
    },
    {
        verbo: 'por', prs_1s: 'ponho',
        prs_3s: 'põe',
        prs_1p: 'pomos',
        prs_3p: 'põem',
        ptp_1s: 'pus',
        ptp_3s: 'pôs',
        ptp_1p: 'pusemos',
        ptp_3p: 'puseram',
        pti_1s: 'punha',
        pti_3s: 'punha',
        pti_1p: 'púnhamos',
        pti_3p: 'punham',
        fps_1s: 'porei',
        fps_3s: 'porá',
        fps_1p: 'poremos',
        fps_3p: 'porão',
        fpt_1s: 'poria',
        fpt_3s: 'poria',
        fpt_1p: 'poríamos',
        fpt_3p: 'poriam'
    },
    {
        verbo: 'ter', prs_1s: 'tenho',
        prs_3s: 'tem',
        prs_1p: 'temos',
        prs_3p: 'têm',
        ptp_1s: 'tive',
        ptp_3s: 'teve',
        ptp_1p: 'tivemos',
        ptp_3p: 'tiveram',
        pti_1s: 'tinha',
        pti_3s: 'tinha',
        pti_1p: 'tínhamos',
        pti_3p: 'tinham',
        fps_1s: 'terei',
        fps_3s: 'terá',
        fps_1p: 'teremos',
        fps_3p: 'terão',
        fpt_1s: 'teria',
        fpt_3s: 'teria',
        fpt_1p: 'teríamos',
        fpt_3p: 'teriam'
    },
];